# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponType', models.CharField(max_length=1)),
                ('couponVal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimumAmt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
