# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BizzyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='couponCode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
